<svelte:head>
  <title>Home</title>
</svelte:head>

<script>
  import Navbar from "../components/navbar.svelte";
  import Footer from "../components/footer.svelte";
  import Background from "../components/background.svelte";
  import Title from "../components/title.svelte";
  import ProjectCard from "../components/project_card.svelte";

  const projects = [
        { 
            id: 3453,
            title: "Lucky Block",
            rating: "4.2",
            description: 'Une plateforme mondiale de jeux et de compétitions avec des joueurs se servant des protocoles de la blockchain.',
            crypto_used : "LBLOCK",
            crypto_link: './images/LBLOCK.png',
            money_earned: 3000,
            goal: 10000,
            total_contributor: 11,
            day_left: 84,
            img_src: './images/LBLOCK_bg.png',
            tag: 'Gaming',
            green: true
        },{
            id: 50,
            title: "Galaxy",
            crypto_used : "GAL",
            crypto_link: './images/GAL.png',
            rating : "4.8",
            description: ' Le projet Galaxy repose sur une infrastructure ouverte et collaborative dont la mission est d\'aider les développeurs Web 3 à utiliser les données d \'accréditation numérique et les NFT pour créer de meilleurs produits et communautés. ',
            money_earned: 1000,
            goal: 7000,
            total_contributor: 841,
            day_left: 2,
            img_src: './images/GAL_bg.jpg',
            tag: 'Marketing'
        }, {
            id: 4545,
            title: "Peermoon",
            crypto_used : "PM",
            crypto_link: 'https://cryptototem.com/wp-content/uploads/2022/01/Peermoon-logo.jpg',
            rating : "4.3",
            description: 'Peermoon is a DeFi mobile wallet that allows you investing and managing your finance conveniently in one app.',
            money_earned: 2500,
            goal: 7000,
            total_contributor: 642,
            day_left: 7,
            img_src: 'https://peermoon.io/wp-content/uploads/2021/12/earth6.png',
            tag: 'Wallet'
        }
  ];

</script>

<Navbar/>
<Background/>
<div class="pt-20 pb-[8rem] lg:pb-10">
    <div class="ml-3 md:ml-64">
        <Title/>
        <h2 class="text-focus-in text-lg md:ml-14 ml-10 font-semibold leading-tight">
          <span class="text-slate-300">
            🚀 Your new cypto launching platform.
          </span>
        </h2>
        <div class="flex text-focus-in2 pt-10">
          <span class="text-slate-300 mt-10 ml-20 font-semibold leading-[2.75rem] shadow border-slate-400 text-xl border p-2 rounded h-60">
              🌍 Explore a large selection of projects and start your own
              <p>
                ⚙️ Easy to use
              </p>
              <p>
                💸 Make profit from investing in your favorite project
              </p>
              <p>
                📝 At a very low cost. Earn from 99% to 99.99% of your donations
              </p>
              <p>
                🌳 We ensure that at least 15% of the projects on our platform are green
              </p>
          </span>
          <div class="h-[40rem] w-[20rem] ml-80 -mt-[2.75rem]">
              <span class="text-slate-300 font-semibold text-lg">
                ⚡ Last projects CrowdCrypto
              </span>
              <div class="h-[40rem] overflow-auto">
              {#each projects as project}
                    <ProjectCard 
                        id={project.id}
                        rating={project.rating}
                        title={project.title}
                        description={project.description}
                        crypto={project.crypto_used}
                        goal={project.goal}
                        money_earned={project.money_earned}
                        img_src={project.img_src}
                        main_page={true}
                        tag={project.tag}
                        green={project.green}
                    />
              {/each}
            </div>
          </div>
        </div>
    </div>
</div>
<Footer/>

<style>
  .text-focus-in {
	-webkit-animation: text-focus-in 4s ease-in-out both;
	        animation: text-focus-in 4s ease-in-out both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-5-14 18:22:22
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */
 @-webkit-keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}
@keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}

.text-focus-in2 {
	-webkit-animation: text-focus-in2 1.6s ease-in both;
	        animation: text-focus-in2 1.6s ease-in both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-5-15 10:58:5
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */
 @-webkit-keyframes text-focus-in2 {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}
@keyframes text-focus-in2 {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}


</style>