<svelte:head>
  <title>Home</title>
</svelte:head>

<script>
  import Navbar from "../components/navbar.svelte";
  import Footer from "../components/footer.svelte";
  import Background from "../components/background.svelte";
  import Title from "../components/title.svelte";
  import ProjectCard from "../components/project_card.svelte";
	import { Parallax, ParallaxLayer } from 'svelte-parallax';

  const projects = [
        { 
            id: 3453,
            title: "Lucky Block",
            rating: "4.2",
            description: 'Une plateforme mondiale de jeux et de compétitions avec des joueurs se servant des protocoles de la blockchain.',
            crypto_used : "LBLOCK",
            crypto_link: './images/LBLOCK.png',
            money_earned: 3000,
            goal: 10000,
            total_contributor: 11,
            day_left: 84,
            img_src: './images/LBLOCK_bg.png'
        },{
            id: 50,
            title: "Galaxy",
            crypto_used : "GAL",
            crypto_link: './images/GAL.png',
            rating : "4.8",
            description: ' Le projet Galaxy repose sur une infrastructure ouverte et collaborative dont la mission est d\'aider les développeurs Web 3 à utiliser les données d \'accréditation numérique et les NFT pour créer de meilleurs produits et communautés. ',
            money_earned: 1000,
            goal: 7000,
            total_contributor: 841,
            day_left: 2,
            img_src: './images/GAL_bg.jpg'
        },{
            id: 46,
            title: "SCOPULY",
            crypto_used : "SCOP",
            crypto_link: './images/SCOP.jpg',
            rating : "0.6",
            description: 'Scopuly is a new DeFi-style digital banking ecosystem built to promote digital lifestyles and enable people to manage their money online – quickly and with minimal fees.',
            money_earned: 300,
            goal: 5000,
            total_contributor: 13,
            day_left: 107,
            img_src: './images/SCOP_bg.jpeg'
        }
  ];

</script>

<Navbar/>
<Background/>
<div class="pt-20 pb-[8rem] lg:pb-10">
    <div class="ml-3 md:ml-64">
        <Title/>
        <h2 class="text-focus-in text-lg md:ml-14 ml-10 font-semibold leading-tight">
          <span class="text-slate-300">
            Your new cypto launching platform.
          </span>
        </h2>
        <div class="flex text-focus-in2 pt-10">
          <span class="text-slate-300 mt-10 ml-20">
              Explore a large selection of projects and start your own.
          </span>
          <div class="h-[40rem] w-[20rem] ml-40 overflow-scroll">
              {#each projects as project}
                    <ProjectCard 
                        id={project.id}
                        rating={project.rating}
                        title={project.title}
                        description={project.description}
                        crypto={project.crypto_used}
                        goal={project.goal}
                        money_earned={project.money_earned}
                        img_src={project.img_src}
                        main_page={true}
                    />
              {/each}
          </div>
        </div>
    </div>
</div>
<Footer/>

<style>
  .text-focus-in {
	-webkit-animation: text-focus-in 4s ease-in-out both;
	        animation: text-focus-in 4s ease-in-out both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-5-14 18:22:22
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */
 @-webkit-keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}
@keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}

.text-focus-in2 {
	-webkit-animation: text-focus-in2 1.6s ease-in both;
	        animation: text-focus-in2 1.6s ease-in both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-5-15 10:58:5
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */
 @-webkit-keyframes text-focus-in2 {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}
@keyframes text-focus-in2 {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}


</style>